version: '3.4'

services:
  mssql:
    container_name: codelytv-chsarp_ddd_skeleton-mssql-vs
    image: mcr.microsoft.com/mssql/server:2019-latest    
    ports:
      - 5400:1433
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=Your_password123
    volumes:
      - ./database/init.sql:/init.sql
      - ./database/mooc.sql:/mooc.sql
      - ./database/backoffice.sql:/backoffice.sql
    restart: unless-stopped
  rabbitmq:
    container_name: codelytv-chsarp_ddd_skeleton-rabbitmq-vs
    image: 'rabbitmq:3.7-management'
    restart: unless-stopped
    ports:
      - 5631:5672
      - 8091:15672
    environment:
      - RABBITMQ_DEFAULT_USER=codelytv
      - RABBITMQ_DEFAULT_PASS=c0d3ly
  elasticsearch:
    container_name: codelytv-chsarp_ddd_skeleton-elasticsearch-vs
    image: 'elasticsearch:7.9.1'
    restart: unless-stopped
    ports:
      - 9300:9300
      - 9200:9200
    environment:
      - discovery.type=single-node

  backoffice-backend:
    container_name: codelytv-chsarp_ddd_skeleton-backoffice_backend-vs
    build:
      context: .
      dockerfile: apps/Backoffice/Backend/Dockerfile
    ports:
      - 8080:80
    depends_on:
      - elasticsearch

  backoffice-frontend-event-consumer:
    container_name: codelytv-chsarp_ddd_skeleton-backoffice_frontend-event-consumer
    build:
      context: .
      dockerfile: apps/Backoffice/Frontend/Dockerfile
      args:
        START_ARGUMENTS: "domain-events:rabbitmq:consume"
    depends_on:
      - mssql
      - rabbitmq
      - elasticsearch

  mooc-backend-event-consumer:
    container_name: codelytv-chsarp_ddd_skeleton-mooc_backend-event-consumer
    build:
      context: .
      dockerfile: apps/Mooc/Backend/Dockerfile
      args:
        START_ARGUMENTS: "domain-events:rabbitmq:consume"
    depends_on:
      - mssql
      - rabbitmq
      - elasticsearch

  mooc-backend:
    container_name: codelytv-chsarp_ddd_skeleton-mooc_backend
    build:
      context: .
      dockerfile: apps/Mooc/Backend/Dockerfile
    depends_on:
      - mssql
      - rabbitmq
      - elasticsearch
    ports:
      - 8012:80

  backoffice-frontend:
    container_name: codelytv-chsarp_ddd_skeleton-backoffice_frontend
    build:
      context: .
      dockerfile: apps/Backoffice/Frontend/Dockerfile
    depends_on:
      - mssql
      - rabbitmq
      - elasticsearch
    ports:
      - 8094:80
